#!/usr/bin/env python3
"""Compute the unpinned (naive-layout) benchmark's RAM flooder size.

Step 7 of plan-mlpCoreLocalPrompt.md needs the naive-layout RAM flooder to
claim whatever space the shared 256 KiB SRAM window has left after every
other static object in the program, so that the flooder and
MLPOpticalRecognition's state end up maximally adjacent under the
compiler/linker's own default (non-per-bank) allocation -- the actual
worst-case layout this benchmark needs to demonstrate contention under. A
fixed guessed size risks leaving enough slack for the two to land
comfortably, under-representing naive-layout interference.

This is a two-pass build: a throwaway probe executable (same sources, a
nominal 1-word flooder via MEML_NAIVE_FLOODER_PROBE_BUILD) is built first;
this script sums that probe's own RAM footprint from its ELF and subtracts
it (plus a safety margin) from the 256 KiB budget to get the real flooder's
byte/word count, then writes a generated header defining it.

Usage:
    compute_naive_flooder_size.py <probe_elf> --readelf <path> --output <path>
"""

import argparse
import re
import subprocess
import sys

RAM0_BASE, RAM0_END = 0x20000000, 0x20040000
RAM_BUDGET_BYTES = RAM0_END - RAM0_BASE  # 256 KiB
DEFAULT_MARGIN_BYTES = 4 * 1024  # matches the pinned build's core-1 stack convention
MIN_USEFUL_FLOOD_BYTES = 4 * 1024

_SECTION_PATTERN = re.compile(
    r"^\s*\[\s*\d+\]\s+(\S+)\s+(\S+)\s+([0-9a-fA-F]+)\s+[0-9a-fA-F]+\s+"
    r"([0-9a-fA-F]+)\s+[0-9a-fA-F]*\s+(\S*)"
)


def run(tool, args):
    result = subprocess.run([tool, *args], capture_output=True, text=True, check=True)
    return result.stdout


def parse_alloc_sections(readelf_output):
    """Return [(name, addr, size)] for every SHF_ALLOC section, from `readelf -SW`."""
    sections = []
    for line in readelf_output.splitlines():
        m = _SECTION_PATTERN.match(line)
        if not m:
            continue
        name, _type, addr_str, size_str, flags = m.groups()
        if "A" not in flags:
            continue  # not allocated at runtime -- irrelevant to the RAM footprint
        sections.append((name, int(addr_str, 16), int(size_str, 16)))
    return sections


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("elf", help="Path to the built probe ELF")
    parser.add_argument("--readelf", default="arm-none-eabi-readelf")
    parser.add_argument("--output", required=True, help="Path to write the generated header")
    parser.add_argument("--margin-bytes", type=int, default=DEFAULT_MARGIN_BYTES)
    args = parser.parse_args()

    sections = parse_alloc_sections(run(args.readelf, ["-SW", args.elf]))

    # Every allocated section whose address falls inside the shared 256 KiB
    # window is part of the probe binary's total RAM footprint under
    # copy_to_ram -- .text/.data/.bss and any orphan-placed section alike.
    probe_footprint_bytes = sum(
        size for _name, addr, size in sections if RAM0_BASE <= addr < RAM0_END
    )

    budget_bytes = RAM_BUDGET_BYTES - probe_footprint_bytes - args.margin_bytes

    if budget_bytes < MIN_USEFUL_FLOOD_BYTES:
        print(
            f"compute_naive_flooder_size: FAIL -- remaining budget {budget_bytes} bytes "
            f"is below the minimum useful flood size {MIN_USEFUL_FLOOD_BYTES} bytes "
            f"(probe footprint={probe_footprint_bytes}, window={RAM_BUDGET_BYTES}, "
            f"margin={args.margin_bytes})",
            file=sys.stderr,
        )
        return 1

    flooder_words = budget_bytes // 4
    flooder_bytes = flooder_words * 4

    print(
        f"naive flooder sizing: probe footprint={probe_footprint_bytes} bytes, "
        f"budget={RAM_BUDGET_BYTES} bytes, margin={args.margin_bytes} bytes, "
        f"flooder={flooder_bytes} bytes ({flooder_bytes / 1024.0:.1f} KiB, "
        f"{flooder_words} words)"
    )

    with open(args.output, "w") as f:
        f.write(
            "// Generated by scripts/compute_naive_flooder_size.py -- do not edit by hand.\n"
            "// Inputs: probe footprint={probe} bytes, 256 KiB budget={budget} bytes, "
            "margin={margin} bytes.\n"
            "#ifndef __MEML_NAIVE_FLOODER_SIZE_HPP__\n"
            "#define __MEML_NAIVE_FLOODER_SIZE_HPP__\n\n"
            "#define MEML_NAIVE_FLOODER_WORDS {words}u\n\n"
            "#endif // __MEML_NAIVE_FLOODER_SIZE_HPP__\n".format(
                probe=probe_footprint_bytes,
                budget=RAM_BUDGET_BYTES,
                margin=args.margin_bytes,
                words=flooder_words,
            )
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
